stages:
  - sync
  - build

variables:
  BUILD_DIR: "/mnt/build"
  INSTALL_DIR: "/mnt/install"
  INSTALL_ARCHIVE: "seaurchin-llvm-assert-install-dev18.tar.zst"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev-18"
      when: always
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - when: never

sync-from-github:
  stage: sync
  image: ubuntu:22.04
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git bash
    - git config --global user.name "GHub to GLab Sync Bot"
    - git config --global user.email "bot@example.com"
  script:
  - |
    export GITHUB_REPO="https://github.com/seahorn/seaurchin-llvm.git"
    export GITLAB_REPO="https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.uwaterloo.ca/seaurchin/seaurchin-llvm.git"
    export SYNC_BRANCH="dev-18"
    git clone --single-branch --branch "$SYNC_BRANCH" "$GITHUB_REPO" github
    cd github
    git remote add gitlab "$GITLAB_REPO"
    echo "Attempting fast-forward-only push from GitHub → GitLab..."
    if git push --ff-only gitlab "$SYNC_BRANCH:$SYNC_BRANCH"; then
      echo "✅ Sync successful."
    else
      echo "❌ Sync failed: GitLab branch is ahead or diverged."
      exit 1
    fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: always
    - when: never

build-seaurchin-llvm-linux:
  stage: build
  image: git.uwaterloo.ca:5050/seaurchin/seaurchin-llvm
  #needs: [prepare]
  script:
    - git checkout dev-18
    - mkdir -p /mnt && chown -R $(id -u):$(id -g) /mnt
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18 -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_FORCE_ENABLE_STATS=ON -DLLVM_INSTALL_UTILS=ON -DLLVM_ENABLE_ZSTD=No -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR llvm -B $BUILD_DIR
    - ninja -v -C $BUILD_DIR
    - ninja -v -C $BUILD_DIR check-llvm
    - ninja -v -C $BUILD_DIR install
    - tar -C /mnt/ -c install/ | zstd -T0 -c > $INSTALL_ARCHIVE
  artifacts:
    paths:
      - $INSTALL_ARCHIVE
    expire_in: 30 days
