
name: Build seaurchin-llvm binaries w assert

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
  push:
    branches:
      - dev-18

jobs:
  build-seaurchin-llvm-linux:
    name: "Build seaurchin-llvm Linux"
    runs-on: seaurchin-big
    if: github.repository == 'seahorn/seaurchin-llvm'
    container:
      image: ghcr.io/seahorn/seaurchin-llvm/buildpack-deps-seaurchin:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      BUILD_DIR: /mnt/build
      INSTALL_DIR: /mnt/install
      INSTALL_ARCHIVE: seaurchin-llvm-assert-install-dev18.tar.zst

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Build/test/install seaurchin-llvm
      run: |
        echo "Showing last 3 commits in LLVM repo:"
        git log -n 3 --oneline
        mkdir -p /mnt && chown -R $(id -u):$(id -g) /mnt
        cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18 -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_FORCE_ENABLE_STATS=ON -DLLVM_INSTALL_UTILS=ON -DLLVM_ENABLE_ZSTD=No -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR llvm -B $BUILD_DIR
        ninja -v -C $BUILD_DIR
        ninja -v -C $BUILD_DIR check-llvm
        ninja -v -C $BUILD_DIR install
        tar -C /mnt/ -c install/ | zstd -T0 -c > $INSTALL_ARCHIVE

    - name: Upload seaurchin-llvm installdir
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: seaurchin-llvm-assert-install
        path: ${{ env.INSTALL_ARCHIVE }}
        retention-days: 30
